/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.giaovien;

import controller.SinhVienController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;
import view.DangNhap;
import view.sinhvien.DangKySinhVien;

/**
 *
 * @author Tuyen
 */
public class QuanLySinhVien extends javax.swing.JFrame {
    
    
    /**
     * Creates new form QuanLySinhVien
     */
    public QuanLySinhVien() throws ClassNotFoundException, SQLException {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        txt_lop = new javax.swing.JTextField();
        txt_matkhau = new javax.swing.JTextField();
        btn_themmoi = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();
        btn_xemdiem = new javax.swing.JButton();
        lb_thongbao = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_masv = new javax.swing.JTextField();
        btn_lammoi = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_dataMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_data);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Quản lý Sinh viên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Lớp:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Mật khẩu:");

        txt_hoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_lop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_matkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_themmoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_themmoi.setText("Thêm mới");
        btn_themmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themmoiActionPerformed(evt);
            }
        });

        btn_sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_timkiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        btn_xemdiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_xemdiem.setText("Xem điểm");

        lb_thongbao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_thongbao.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mã sinh viên:");

        txt_masv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_lammoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_lammoi.setText("Làm mới ");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_xemdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_themmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_lop, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_thongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_thongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xemdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_dataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseReleased
        // TODO add your handling code here:
        int row = tbl_data.getSelectedRow();
        txt_masv.setText(tbl_data.getValueAt(row, 0).toString()) ;
        txt_hoten.setText(tbl_data.getValueAt(row, 1).toString());
        txt_lop.setText(tbl_data.getValueAt(row, 2).toString());
        txt_matkhau.setText(tbl_data.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbl_dataMouseReleased

    private void btn_themmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themmoiActionPerformed
        // TODO add your handling code here:
        String maSV = txt_masv.getText();
        String hoten = txt_hoten.getText();
        String lop = txt_lop.getText();
        String matkhau = txt_matkhau.getText();
        
        if (maSV.equals("") || hoten.equals("") || lop.equals("") || matkhau.equals("")) {
            lb_thongbao.setText("Tất cả các trường không được bỏ trống");
        }else{
            SinhVien sv = new SinhVien(lop, maSV, matkhau, hoten);
            try {
                int i = sinhvienCtr.dangky(sv);
                if (i == 0) {
                    lb_thongbao.setText("Mã sinh viên đã có người sử dụng, hãy nhập lại");
                }
                if (i == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm mới thành công");
                    loadData();
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_themmoiActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        String maSV = txt_masv.getText();
        if (maSV.equals("")) {
            lb_thongbao.setText("Bạn cần chọn một sinh viên để xóa");
        } else {
            int click = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn xóa?");
            if (click == JOptionPane.YES_OPTION) {
                try {
                    int i = sinhvienCtr.xoa(maSV);
                    if (i == 0) {
                        lb_thongbao.setText("Không có mã sinh viên như trên, hãy nhập lại");
                    }
                    if (i == 1) {
                        JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                        loadData();
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        try {
            // TODO add your handling code here:
            loadData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        String maSV = txt_masv.getText();
        String hoten = txt_hoten.getText();
        String lop = txt_lop.getText();
        String matkhau = txt_matkhau.getText();
        if (maSV.equals("")) {
            lb_thongbao.setText("Bạn cần chọn một sinh viên để sửa");
        }else if (hoten.equals("")|| lop.equals("") || matkhau.equals("")) {
            lb_thongbao.setText("Tất cả các trường không được bỏ trống");
        }else{
            SinhVien sv = new SinhVien(lop, maSV, matkhau, hoten);
            try {
                int i = sinhvienCtr.sua(sv);
                if (i == 0) {
                    lb_thongbao.setText("Không có mã sinh viên như trên, hãy nhập lại");
                }
                if (i == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
                    loadData();
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(DangKySinhVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String maSV = txt_masv.getText();
        String hoten = txt_hoten.getText();
        if (maSV.equals("") && hoten.equals("")) {
            lb_thongbao.setText("Bạn cần nhập Mã sinh viên hoặc họ tên");
        } else {
            try {
                dsSinhVien = sinhvienCtr.timkiem(maSV, hoten);
                loadDataTimkiem(dsSinhVien);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
//        try {
//            dsSinhVien = sinhvienCtr.timkiem(sv);
//            loadDataTimkiem(dsSinhVien);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_btn_timkiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuanLySinhVien().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_themmoi;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xemdiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_thongbao;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_lop;
    private javax.swing.JTextField txt_masv;
    private javax.swing.JTextField txt_matkhau;
    // End of variables declaration//GEN-END:variables
    
    private SinhVienController sinhvienCtr = new SinhVienController();
    ArrayList<SinhVien> dsSinhVien = new ArrayList<SinhVien>();
    DefaultTableModel modelSinhVien;
    
    public void loadData() throws ClassNotFoundException, SQLException{
        txt_masv.setText("");
        txt_hoten.setText("");
        txt_lop.setText("");
        txt_matkhau.setText("");
        lb_thongbao.setText("");
        
        modelSinhVien = new DefaultTableModel();
        modelSinhVien.addColumn("Mã sinh viên");
        modelSinhVien.addColumn("Họ tên");
        modelSinhVien.addColumn("Lớp");
        modelSinhVien.addColumn("Mật khẩu");
        //Load data vào bảng
        dsSinhVien = sinhvienCtr.danhsachSinhVien();
        for (int i = 0; i < dsSinhVien.size(); i++) {
            SinhVien sv = dsSinhVien.get(i);
            Object[] rowData = {
                sv.getId(), sv.getHoten(), sv.getLop(), sv.getMatkhau()
            };
            modelSinhVien.addRow(rowData);
        }
        tbl_data.setModel(modelSinhVien);
    }
    
    public void loadDataTimkiem(ArrayList<SinhVien> list){
        modelSinhVien = new DefaultTableModel();
        modelSinhVien.addColumn("Mã sinh viên");
        modelSinhVien.addColumn("Họ tên");
        modelSinhVien.addColumn("Lớp");
        modelSinhVien.addColumn("Mật khẩu");
        
        //Load data vào bảng
        for (int i = 0; i < list.size(); i++) {
            SinhVien sv = list.get(i);
            Object[] rowData = {
                sv.getId(), sv.getHoten(), sv.getLop(), sv.getMatkhau()
            };
            modelSinhVien.addRow(rowData);
        }
        tbl_data.setModel(modelSinhVien);
    }
     
}
