/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sinhvien;

import controller.ChiTietDeThiController;
import controller.KetQuaController;
import entity.SaveDeThi;
import entity.SaveSinhVien;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.CauHoi;
import model.DeThi;
import model.KetQua;

/**
 *
 * @author Tuyen
 */
public class Thi extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Thi
     */
    public Thi() throws ClassNotFoundException, SQLException {
        initComponents();
        lb_maDT.setText(dethi.getMaDT());
        threadThi = new Thread(this);
        threadThi.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lb_number = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_maDT = new javax.swing.JLabel();
        lb_ch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_cauhoi = new javax.swing.JTextArea();
        rd_A = new javax.swing.JRadioButton();
        rd_B = new javax.swing.JRadioButton();
        rd_C = new javax.swing.JRadioButton();
        rd_D = new javax.swing.JRadioButton();
        lb_luachonA = new javax.swing.JLabel();
        lb_luachonB = new javax.swing.JLabel();
        lb_luachonC = new javax.swing.JLabel();
        lb_luachonD = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_nopbai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_number.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("HỆ THỐNG THI TRẮC NGHIỆM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã đề thi:");

        lb_maDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lb_ch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_cauhoi.setColumns(20);
        txt_cauhoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cauhoi.setRows(5);
        jScrollPane1.setViewportView(txt_cauhoi);

        buttonGroup1.add(rd_A);
        rd_A.setText("A");
        rd_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_AActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd_B);
        rd_B.setText("B");

        buttonGroup1.add(rd_C);
        rd_C.setText("C");
        rd_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_CActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd_D);
        rd_D.setText("D");

        lb_luachonA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lb_luachonB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lb_luachonC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lb_luachonD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Thời gian:");

        btn_nopbai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_nopbai.setText("Nộp bài");
        btn_nopbai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nopbaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_ch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_maDT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rd_A)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_luachonA, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rd_C)
                                    .addComponent(rd_D)
                                    .addComponent(rd_B))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btn_nopbai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_number, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lb_luachonD, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_luachonC, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_luachonB, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_maDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_A, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_luachonA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd_B, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_luachonB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rd_C, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_luachonC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_luachonD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_D, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_nopbai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rd_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_CActionPerformed

    private void rd_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_AActionPerformed

    private void btn_nopbaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nopbaiActionPerformed
        try {
            threadThi.stop();
            // TODO add your handling code here:
            KetQua kq = new KetQua(SaveSinhVien.maSV, dethi.getMaMH(), diem);
            ketquaCtr.them(kq);
            JOptionPane.showMessageDialog(rootPane, "Đã lưu kết quả");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Thi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Thi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_nopbaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Thi().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Thi.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Thi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nopbai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_ch;
    private javax.swing.JLabel lb_luachonA;
    private javax.swing.JLabel lb_luachonB;
    private javax.swing.JLabel lb_luachonC;
    private javax.swing.JLabel lb_luachonD;
    private javax.swing.JLabel lb_maDT;
    private javax.swing.JLabel lb_number;
    private javax.swing.JRadioButton rd_A;
    private javax.swing.JRadioButton rd_B;
    private javax.swing.JRadioButton rd_C;
    private javax.swing.JRadioButton rd_D;
    private javax.swing.JTextArea txt_cauhoi;
    // End of variables declaration//GEN-END:variables
    
    private static Thread threadThi;
    private float diem = 0;
    private DeThi dethi = new DeThi(SaveDeThi.maDT, SaveDeThi.maMH, SaveDeThi.thoigianlammoicau);
    private ChiTietDeThiController chitietdethiCtr = new ChiTietDeThiController();
    private ArrayList<CauHoi> dsCauHoi = new ArrayList<>();
    private KetQuaController ketquaCtr = new KetQuaController();
    
    @Override
    public void run() {
        try {
            dsCauHoi = chitietdethiCtr.danhsachChiTietDeThi(dethi.getMaDT());

            for (int i = 0; i < dsCauHoi.size(); i++) {
                System.out.println("diem: "+ diem);
                
                rd_A.setSelected(false);
                rd_B.setSelected(false);
                rd_C.setSelected(false);
                rd_D.setSelected(false);
                CauHoi ch = dsCauHoi.get(i);
                lb_ch.setText("Câu hỏi "+(i+1));
                txt_cauhoi.setText(ch.getNoidung());
                lb_luachonA.setText(ch.getDapanA());
                lb_luachonB.setText(ch.getDapanB());
                lb_luachonC.setText(ch.getDapanC());
                lb_luachonD.setText(ch.getDapanD());
                
                for (int j = dethi.getThoigianlammoicau(); j > 0; j--) {
                    lb_number.setText(String.valueOf(j));
                    Thread.sleep(1000);
                }
                
                if (ch.getDapandung().equals("A") && rd_A.isSelected()) {
                    diem++;
                }
                if (ch.getDapandung().equals("B") && rd_B.isSelected()) {
                    diem++;
                }
                if (ch.getDapandung().equals("C") && rd_C.isSelected()) {
                    diem++;
                }
                if (ch.getDapandung().equals("D") && rd_D.isSelected()) {
                    diem++;
                }
            }
            JOptionPane.showInternalMessageDialog(rootPane, "Điểm của bạn: "+ diem);
        } catch (ClassNotFoundException | SQLException | InterruptedException ex) {
            Logger.getLogger(Thi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loadData() throws ClassNotFoundException, SQLException{
        dsCauHoi = chitietdethiCtr.danhsachChiTietDeThi(dethi.getMaDT());
        for (int i = 0; i < dsCauHoi.size(); i++) {
            CauHoi ch = dsCauHoi.get(i);
            System.out.println(ch);
        }
    }




}
